# Generated by Django 3.1.3 on 2020-11-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
